name: Node Continuous Integration
on: push
jobs:
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install
      - uses: org-name/repo-name@v0
        with:
          property: value    
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/
